[package]
name = "010devx101/lyra"
description = "Advanced player data management with a simple API. Updated to the new solver, exposed types and useful functions that used to be private"
version = "0.6.1-patch.2"
license = "MIT"
authors = ["nomer888", "outofbears"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://paradoxum-games.github.io/lyra/"
repository = "https://github.com/010devx101/lyra"
exclude = ["*"]
include = [
	"src",
	"src/**/*",
	"wally.lock",
	"wally.toml",
	"LICENSE",
	"default.project.json",
]

[dependencies]
Promise = "evaera/promise@4.0.0"
GreenTea = "corecii/greentea@0.4.11"

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
